### ISSUE TITLE
ImportError: cannot import name 'Conv2d' from 'network'

### ISSUE THREAD

**Issue by Akbarkhan87** [WangyiNTU/SCALNet#2]
When I want to run this piece of code it throws an error 

python train.py --model DLANet --dataset NWPU --batch_size 32 --loss LocLoss --gpus 0 --lr 0.0001 --epochs 20 --save_model_interval 2 --preload --save

ImportError: cannot import name 'Conv2d' from 'network'

**Comment by akx** [comment]
As discussed on https://stackoverflow.com/a/68451495/51685, this is likely due to running the program on Python 3 and having a `network` module installed in `site-packages`.

**Comment by WangyiNTU** [comment]
@Akbarkhan87 Yes, as @akx mentioned. I built the project with Python 2.7. Thanks for your answer.
